---
    - name: Install epel-release
      yum: name=http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present 
    - name: Install nginx
      yum: name=nginx state=present
    - name: Download Kibana
      get_url: url='https://download.elastic.co/kibana/kibana/kibana-4.1.2-linux-x64.tar.gz' dest=/tmp/kibana.tar.gz
      
    - name: Extract and install Kibana
      unarchive: src=/tmp/kibana.tar.gz
             dest=/opt
             copy=no
             creates=/opt/kibana      
    
    - name: Check Kibana Folder
      stat: path=/opt/kibana-4.1.2-linux-x64
      register: kibana_stat

    - name: Move Kibana Folder
      command: mv /opt/kibana-4.1.2-linux-x64 /opt/kibana
      when: kibana_stat.stat.exists
        
    - name: Configure Kibana service definition
      template: src=kibana.j2 dest=/etc/init.d/kibana mode=0755

    - name: Ensure kibana's nginx site is in place
      template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/kibana.conf mode=0755

    - name: Ensure kibana's htpasswd file is in place
      copy: src=htpasswd.users dest=/etc/nginx/htpasswd.users mode=0644 owner=root group=root

    - name: Ensure default nginx site is not enabled
      file: state=absent path=/etc/nginx/conf.d/default.conf

    - name: Ensure default nginx site is not enabled
      file: state=absent path=/etc/nginx/conf.d/ssl.conf
    
    - name: Ensure default nginx site is not enabled
      file: state=absent path=/etc/nginx/conf.d/virtual.conf    

    - name: Create Kibana Config
      template: src=kibana.yml.j2 dest=/opt/kibana/config/kibana.yml
    
    - name: Open the correct IPTables ports
      lineinfile: dest=/etc/sysconfig/iptables
                  regexp="^-A INPUT -p {{item.protocol}} -m {{item.protocol}} --dport {{item.port}} -j ACCEPT$"
                  line="-A INPUT -p {{item.protocol}} -m {{item.protocol}} --dport {{item.port}} -j ACCEPT"
                  insertafter="^:OUTPUT ACCEPT \[\d*:\d*\]$"
      with_items:
        - { protocol: tcp, port: 80 }
        
      notify:
        - Restart iptables         
    
    - name: ensure Kibana is running (and automatically at boot time)
      action: service name=kibana enabled=yes state=restarted  

    - name: ensure Nginx is running (and automatically at boot time)
      action: service name=nginx enabled=yes state=restarted  
  
